const { chromium } = await import(process.env.SPA_PLAYWRIGHT_MODULE || 'playwright');
import { PGlite } from '@electric-sql/pglite';
import {fileURLToPath} from 'node:url';
import { spawn } from 'node:child_process';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {taipeiDate,dateAfter} from '../src/lib/date-range.js';
const source=fileURLToPath(new URL('..',import.meta.url));
process.chdir(source);
const db=new PGlite();let queue=Promise.resolve();
const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;};
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
for(const m of ['202610010001_spa_operations.sql','202610010002_legacy_import.sql','202610010003_customer_booking.sql'])await db.exec(await readFile(source+'/supabase/migrations/'+m,'utf8'));
const owner=randomUUID();await db.query('insert into auth.users(id) values($1)',[owner]);await db.query("insert into spa_roles(user_id,role) values($1,'owner')",[owner]);
const fnMap=new Map((await db.query("select p.proname,p.proargnames,p.proretset from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'spa_%'")).rows.map(r=>[r.proname,r]));
async function call(fn,args={},authenticated=false){return serial(async()=>{await db.exec('begin');try{await db.exec('set local role '+(authenticated?'authenticated':'anon'));await db.query("select set_config('request.jwt.claim.sub',$1,true)",[authenticated?owner:'']);const meta=fnMap.get(fn);if(!meta)throw Error('Unknown RPC: '+fn);const keys=Object.keys(args);for(const k of keys)if(!meta.proargnames?.includes(k))throw Error('Unknown parameter: '+k);const named=keys.map((k,i)=>k+'=> $'+(i+1)).join(',');const q=meta.proretset?'select * from public.'+fn+'('+named+')':'select public.'+fn+'('+named+') result';const r=await db.query(q,keys.map(k=>args[k]));await db.exec('commit');return meta.proretset?r.rows:r.rows[0]?.result;}catch(e){await db.exec('rollback');throw e;}});}
const catalog=await call('spa_catalog'),today=taipeiDate(),day=dateAfter(2),next=dateAfter(3),service=catalog.services[0].id;
async function seed(at,phone='0988000001',name='手機測試客'){const r=await call('spa_create_booking',{p_request:randomUUID(),p_service:service,p_date:day,p_start:day+'T'+at+':00+08:00',p_staff:null,p_name:name,p_phone:phone,p_tea:0,p_note:'瀏覽器測試'});return (await db.query('select * from spa_appointments where manage_token=$1',[r.manage_token])).rows[0];}
const rescheduled=await seed('12:00'),cancelled=await seed('14:00'),past=await seed('16:00'),completed=await seed('18:00'),alreadyCancelled=await seed('20:00');
await db.query("update spa_appointments set starts_at=now()-interval '10 days',ends_at=now()-interval '10 days'+interval '45 minutes',blocked_until=now()-interval '10 days'+interval '1 hour',business_date=$2 where id=$1",[past.id,dateAfter(-10)]);
await db.query("update spa_appointments set starts_at=now()-interval '9 days',ends_at=now()-interval '9 days'+interval '45 minutes',blocked_until=now()-interval '9 days'+interval '1 hour',business_date=$2,status='completed' where id=$1",[completed.id,dateAfter(-9)]);
await call('spa_cancel_booking',{p_token:alreadyCancelled.manage_token,p_reason:'預先取消'});
const server=spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4175','--strictPort'],{cwd:source,stdio:'ignore'});process.on('exit',()=>server.kill());
for(let i=0;i<40;i++){try{await fetch('http://127.0.0.1:4175/');break;}catch{await new Promise(r=>setTimeout(r,100));}}
const browser=await chromium.launch({headless:true,...(process.env.SPA_BROWSER_EXECUTABLE?{executablePath:process.env.SPA_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
const errors=[],rpcLog=[],overflows=[];let assertions=0,serverTime=null;
const check=(v,msg)=>{assert.ok(v,msg);assertions++;};
const user={id:owner,email:'owner@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{},created_at:new Date().toISOString()};
const jwt='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.'+Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url')+'.test';
async function context(options={}){const ctx=await browser.newContext({viewport:{width:390,height:844},timezoneId:'America/Los_Angeles',...options});if(process.env.SPA_QA_FONT)await ctx.addInitScript(()=>window.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent="@font-face{font-family:'Noto Serif TC';src:url('/qa-font.ttf')}@font-face{font-family:'Noto Sans TC';src:url('/qa-font.ttf')}";document.head.append(s);}));await ctx.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.hostname==='127.0.0.1'){if(u.pathname==='/qa-font.ttf'&&process.env.SPA_QA_FONT)return route.fulfill({path:process.env.SPA_QA_FONT,contentType:'font/ttf'});return route.continue();}if(!u.hostname.endsWith('.supabase.co'))return route.abort();const send=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});if(u.pathname==='/auth/v1/token')return send({access_token:jwt,refresh_token:'qa-refresh',token_type:'bearer',expires_in:3600,user});if(u.pathname==='/auth/v1/user')return send(user);const fn=u.pathname.split('/').pop(),args=req.postDataJSON()||{};rpcLog.push({fn,args});try{return send(fn==='spa_server_time'&&serverTime?serverTime:await call(fn,args,req.headers().authorization==='Bearer '+jwt));}catch(e){return send({code:e.code||'XX000',message:e.message},400);}});ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));return ctx;}
async function overflow(page,scope,label){const result=await page.locator(scope).evaluateAll(els=>els.flatMap(root=>[root,...root.querySelectorAll('h1,h2,h3,p,button,input,select,textarea,label,a,.booking-progress-item,.formula-name,.hero-fancy,.hero-subtitle-text')]).filter(el=>{const style=getComputedStyle(el),r=el.getBoundingClientRect();return !el.closest('[aria-hidden="true"]')&&!el.classList.contains('fb-trap')&&style.display!=='none'&&style.visibility!=='hidden'&&r.width>0&&(r.left<-.6||r.right>innerWidth+.6);}).map(el=>({tag:el.tagName,class:el.className,text:el.textContent.slice(0,45),left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right})));overflows.push({label,result});check(result.length===0,label+' fits viewport: '+JSON.stringify(result).slice(0,500));check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+.5),label+' document width');}
async function anchor(page,label){await page.waitForFunction(()=>{const a=document.querySelector('.booking-anchor'),n=document.querySelector('.public-nav');return a&&Math.abs(a.getBoundingClientRect().top-n.getBoundingClientRect().height-16)<3;});check(await page.evaluate(()=>document.querySelector('.booking-anchor').getBoundingClientRect().top>0&&scrollY<document.documentElement.scrollHeight-innerHeight-100),label+' stays at booking heading, away from footer');}
await mkdir('qa-mobile',{recursive:true});
try{
const adminContext=await context({viewport:{width:1440,height:1000}}),admin=await adminContext.newPage();
await admin.goto('http://127.0.0.1:4175/#admin');await admin.getByLabel('使用者名稱或電子郵件').fill(user.email);await admin.getByLabel('密碼').fill('QA-only');await admin.getByRole('button',{name:'登入',exact:true}).click();await admin.getByText('範圍內預約',{exact:true}).waitFor();check(await admin.getByLabel('開始日期',{exact:true}).inputValue()===today,'admin Taiwan default today');check(await admin.getByLabel('結束日期',{exact:true}).inputValue()===dateAfter(6),'admin inclusive week');
const frontContext=await context({viewport:{width:320,height:780},isMobile:true,hasTouch:true}),front=await frontContext.newPage();
await front.goto('http://127.0.0.1:4175/');await overflow(front,'#root','320px complete homepage');await front.getByRole('button',{name:'預約體驗',exact:true}).click();await anchor(front,'hero navigation');await overflow(front,'.booking-section','320px step 1');await front.screenshot({path:'qa-mobile/booking-320.png'});
await front.locator('.booking-service-options .service-card').first().click();await front.getByRole('button',{name:'下一步',exact:true}).click();await anchor(front,'step 2');await overflow(front,'.booking-section','320px step 2');await front.getByText('不指定技師',{exact:true}).click();await front.getByRole('button',{name:'下一步',exact:true}).click();await anchor(front,'step 3');await overflow(front,'.booking-section','320px step 3');
await front.getByRole('button',{name:next,exact:true}).click();await front.getByText('10:00',{exact:true}).click();await front.getByRole('button',{name:'下一步',exact:true}).click();await anchor(front,'step 4');await overflow(front,'.booking-section','320px step 4 confirmation');check(await front.locator('.booking-progress-item').count()===4,'Chinese wizard has four steps');check(await front.getByText('療程搭配養生茶飲',{exact:true}).count()===0,'tea selection step removed');await front.getByRole('button',{name:'上一步',exact:true}).click();await front.getByText('10:00',{exact:true}).waitFor();check(await front.getByPlaceholder('您的姓名').count()===0,'confirmation back returns directly to time selection');await front.getByRole('button',{name:'下一步',exact:true}).click();await front.getByPlaceholder('您的姓名').fill('新增手機客');await front.getByPlaceholder('您的手機號碼').fill('0988000008');await front.getByRole('button',{name:'確認預約',exact:true}).click();await front.getByText('預約已送出，等待門店確認',{exact:true}).waitFor();await anchor(front,'booking success');const created=(await db.query("select a.id,a.reference,a.tea_code,a.tea_cents,a.price_cents from spa_appointments a join spa_customers c on c.id=a.customer_id where c.phone='0988000008'")).rows[0];check(!!created,'public wizard creates real database row');check(created.tea_code===0&&Number(created.tea_cents)===0&&Number(created.price_cents)===Number(catalog.services[0].price_cents),'four-step booking charges only the therapy price');await admin.evaluate(()=>window.dispatchEvent(new Event('focus')));await admin.getByText(created.reference,{exact:true}).waitFor();assertions++;
await front.getByRole('tab',{name:'查詢預約',exact:true}).click();await anchor(front,'lookup mode');await front.getByLabel('手機號碼',{exact:true}).fill('0988000001');await front.getByLabel('預約姓名',{exact:true}).fill('錯誤姓名');await front.locator('.lookup-form').getByRole('button',{name:'查詢預約',exact:true}).click();await front.getByText('未找到符合的預約，請確認手機與姓名。',{exact:true}).waitFor();check(await front.locator('.lookup-card').count()===0,'wrong full name does not reveal bookings');await front.getByLabel('預約姓名',{exact:true}).fill('手機測試客');await front.locator('.lookup-form').getByRole('button',{name:'查詢預約',exact:true}).click();await front.getByRole('tab',{name:'Active · 有效預約 (2)',exact:true}).waitFor();check(await front.getByRole('tab',{name:'Nonactive · 已結束／取消 (3)',exact:true}).count()===1,'past, completed and cancelled grouped Nonactive');await overflow(front,'.booking-section','320px lookup active');
console.log('UI: wizard + lookup passed');const move=front.locator(`[data-booking-id="${rescheduled.id}"]`);await move.getByRole('button',{name:'改期預約',exact:true}).click();await move.getByLabel('新日期',{exact:true}).fill(next);await move.getByLabel('可用時段',{exact:false}).selectOption({label:'12:00'});await move.getByLabel('改期原因',{exact:true}).fill('想改成隔天');await move.getByRole('button',{name:'確認改期',exact:true}).click();await front.getByRole('status').filter({hasText:'改期已送出'}).waitFor();await admin.evaluate(()=>window.dispatchEvent(new Event('focus')));const changedAdmin=admin.locator(`[data-booking-id="${rescheduled.id}"]`);await changedAdmin.getByText(new RegExp(next.split('-').map(Number).join('/'))).waitFor();check((await db.query('select business_date::text from spa_appointments where id=$1',[rescheduled.id])).rows[0].business_date===next,'UI reschedule saves same database row');
console.log('UI: reschedule passed');const cancel=front.locator(`[data-booking-id="${cancelled.id}"]`);await cancel.getByRole('button',{name:'取消預約',exact:true}).click();await cancel.getByLabel('取消原因',{exact:true}).fill('行程調整');await cancel.getByRole('button',{name:'確認取消',exact:true}).click();await front.getByRole('status').filter({hasText:'預約已取消'}).waitFor();check(await front.locator(`[data-booking-id="${cancelled.id}"].is-inactive`).count()===1,'cancelled result immediately becomes gray Nonactive');await admin.evaluate(()=>window.dispatchEvent(new Event('focus')));await admin.locator(`[data-booking-id="${cancelled.id}"].booking-inactive`).waitFor();check((await db.query('select status from spa_appointments where id=$1',[cancelled.id])).rows[0].status==='cancelled','UI cancellation reaches real database');
await front.screenshot({path:'qa-mobile/lookup-320.png',fullPage:false});await admin.getByLabel('開始日期',{exact:true}).fill(dateAfter(-10));await admin.locator(`[data-booking-id="${past.id}"].booking-inactive`).waitFor();await admin.locator(`[data-booking-id="${completed.id}"].booking-inactive`).waitFor();assertions+=2;
console.log('UI: cancellation passed');for(const width of [320,360,390,430,768,1440]){await front.setViewportSize({width,height:900});await overflow(front,'.booking-section',width+'px lookup inactive');await admin.setViewportSize({width,height:900});await overflow(admin,'.ops main',width+'px admin');}
await front.setViewportSize({width:390,height:844});await front.locator('.lookup-card').first().scrollIntoViewIfNeeded();await front.screenshot({path:'qa-mobile/query-mobile.png'});await admin.setViewportSize({width:390,height:844});await admin.locator('[data-booking-id="'+cancelled.id+'"]').scrollIntoViewIfNeeded();await admin.screenshot({path:'qa-mobile/admin-gray-mobile.png'});
console.log('UI: widths passed');
await admin.getByRole('button',{name:'查看排程',exact:true}).click();await admin.locator('.schedule .booking-inactive').first().waitFor();check(await admin.locator('.schedule .booking-inactive').first().evaluate(el=>getComputedStyle(el).backgroundColor)==='rgb(35, 36, 33)','calendar inactive card uses gray background');await admin.getByRole('button',{name:'查看列表',exact:true}).click();
// Existing receipt links allow one appointment only and now support rescheduling.
const linkPage=await frontContext.newPage();await linkPage.goto('http://127.0.0.1:4175/#manage/'+rescheduled.manage_token);await linkPage.getByRole('tab',{name:'Active · 有效預約 (1)',exact:true}).waitFor();check(await linkPage.locator('.lookup-card').count()===1,'receipt link sees one appointment');await overflow(linkPage,'.lookup-page','390px private link');
// Deliberately wrong device clock: server time still determines classification. Then cross the service end.
await linkPage.clock.install({time:new Date('2036-01-01T00:00:00Z')});const firstClock=linkPage.waitForResponse(r=>r.url().endsWith('/spa_server_time'));await linkPage.evaluate(()=>window.dispatchEvent(new Event('focus')));await firstClock;await linkPage.clock.runFor(1100);await linkPage.getByRole('tab',{name:'Active · 有效預約 (1)',exact:true}).waitFor();assertions++;const dbMoved=(await db.query('select ends_at from spa_appointments where id=$1',[rescheduled.id])).rows[0];serverTime=new Date(Date.parse(dbMoved.ends_at)+2000).toISOString();const expiredClock=linkPage.waitForResponse(r=>r.url().endsWith('/spa_server_time'));await linkPage.evaluate(()=>window.dispatchEvent(new Event('focus')));await expiredClock;await linkPage.clock.runFor(1100);await linkPage.getByRole('tab',{name:'Nonactive · 已結束／取消 (1)',exact:true}).waitFor();await linkPage.getByRole('tab',{name:/Nonactive/}).click();check(await linkPage.locator('.is-inactive').count()===1,'server-time expiry becomes gray without reloading');check((await db.query('select status from spa_appointments where id=$1',[rescheduled.id])).rows[0].status==='pending','visual expiry does not invent completed database status');serverTime=null;
// Other public pages and English four-step labels on all phone widths.
const freshContext=await context();for(const width of [320,390,430]){const p=await freshContext.newPage();await p.setViewportSize({width,height:844});for(const route of ['#shop','#contact','#member','#lookup']){await p.goto('http://127.0.0.1:4175/'+route);await p.locator(route==='#member'?'.login':route==='#lookup'?'.lookup-form':'.public-page-nav').waitFor();await overflow(p,route==='#member'?'.ops':route==='#lookup'?'.lookup-page':route==='#shop'?'.shop-card,.public-page-nav':'#root',width+'px '+route);}await p.goto('http://127.0.0.1:4175/');await p.locator('.mobile-menu-btn').click();await p.locator('.mobile-nav').getByText('EN',{exact:true}).click();await p.getByRole('button',{name:'Book Now',exact:true}).click();await anchor(p,'English hero '+width);await overflow(p,'#root',width+'px English homepage');await overflow(p,'.booking-section',width+'px English wizard');await p.locator('.booking-service-options .service-card').first().click();await p.getByRole('button',{name:'Next',exact:true}).click();await anchor(p,'English step 2');await overflow(p,'.booking-section',width+'px English therapists');await p.getByText('No Preference',{exact:true}).click();await p.getByRole('button',{name:'Next',exact:true}).click();await p.getByRole('button',{name:next,exact:true}).click();await p.getByText('10:00',{exact:true}).click();await overflow(p,'.booking-section',width+'px English time slots');await p.getByRole('button',{name:'Next',exact:true}).click();await overflow(p,'.booking-section',width+'px English confirmation');check(await p.locator('.booking-progress-item').count()===4,'English wizard has four steps');check(await p.getByRole('button',{name:'Confirm Booking',exact:true}).count()===1,'English time selection goes directly to confirmation');await p.close();}
check(errors.length===0,'no browser runtime errors: '+errors.join(';'));console.log('PASS: '+assertions+' browser assertions against real PostgreSQL RPC functions.');await writeFile('qa-mobile/validation.json',JSON.stringify({assertions,errors,rpcCount:rpcLog.length,overflows},null,2));
}catch(e){for(const ctx of browser.contexts())for(const [i,p] of ctx.pages().entries()){console.log('FAILED PAGE',p.url(),(await p.locator('body').innerText()).slice(-1500));await p.screenshot({path:'qa-mobile/failure-'+i+'.png'});}throw e;}finally{await browser.close();server.kill();await db.close();}
