import {useEffect,useRef,useState} from 'react';
import {rpc,dateTime,errorText,taipeiDate,exportCSV} from './lib/spa.js';
import {attendanceStatuses,attendanceFlags,attendanceMinutes,taipeiInput,attendanceStamp,getPunchLocation,canPunch} from './lib/attendance.js';
import {Field,Modal,MutationForm,Empty} from './OperationsShared.jsx';
import './attendance.css';

function useAttendance(name,from,to){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const sequence=useRef(0);
 async function load(){const id=++sequence.current;setLoading(true);try{const next=await rpc(name,{p_from:from,p_to:to});if(id===sequence.current){setData(next);setError('');}return next;}catch(e){if(id===sequence.current)setError(errorText(e));return null;}finally{if(id===sequence.current)setLoading(false);}}
 useEffect(()=>{setData(null);load();return()=>{sequence.current++;};},[name,from,to]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')load();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);const timer=setInterval(refresh,60000);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);clearInterval(timer);};},[name,from,to]);
 return {data,error,loading,load};
}
function Flags({flags=[]}){return <div className="attendance-flags">{(flags||[]).map(flag=><span className="badge" key={flag}>{attendanceFlags[flag]||flag}</span>)}</div>;}
function Evidence({events=[]}){return <details className="attendance-evidence"><summary>原始打卡與定位紀錄</summary>{events.length?events.map(e=><div key={e.id}><strong>{e.kind==='in'?'上班':'下班'} · {dateTime(e.recorded_at)}</strong><p>{e.distance_m==null?'未取得定位':`距門店 ${Math.round(e.distance_m)} 公尺 · 定位誤差 ±${Math.round(e.accuracy_m)} 公尺`}</p>{e.latitude!=null&&<a href={`https://www.google.com/maps?q=${e.latitude},${e.longitude}`} target="_blank" rel="noreferrer">查看打卡位置（Google 地圖）</a>}{e.reason&&<p>員工說明：{e.reason}</p>}<Flags flags={e.flags}/><small className="muted">當時範圍：{e.geofence_snapshot.radius_m} 公尺 · {e.geofence_snapshot.address}</small></div>):<p className="muted">此筆為補打卡，沒有原始定位紀錄。</p>}</details>;}
function AttendanceRow({row,events,action}){return <article className={`attendance-row ${row.status}`}><div className="row"><strong>{row.employee?`${row.employee} · `:''}{row.work_date}</strong><span className="badge">{attendanceStatuses[row.status]}</span></div><p>原始上班：{row.clock_in?dateTime(row.clock_in):'補打卡'}<br/>原始下班：{row.clock_out?dateTime(row.clock_out):(row.clock_in?'尚未打下班卡':'補打卡')}</p><p className="muted">核算時段：{row.effective_start?dateTime(row.effective_start):'—'} ～ {row.effective_end?dateTime(row.effective_end):'—'} · 休息 {row.break_minutes} 分鐘{row.effective_end&&<> · 淨工時 {attendanceMinutes(row)} 分鐘</>}</p>{row.shift_start&&<p className="muted">打卡時班表：{dateTime(row.shift_start)} ～ {dateTime(row.shift_end)}</p>}<Flags flags={row.flags}/>{row.review_note&&<p>審核說明：{row.review_note}</p>}{row.time_entry_id&&row.status==='approved'&&<small className="muted">已連動薪資工時 · {row.time_entry_id.slice(0,8)}</small>}<Evidence events={events}/>{action}</article>;}

export function AttendanceEmployee({from,to}){
 const {data,error,loading,load}=useAttendance('spa_attendance_self',from,to),[reason,setReason]=useState(''),[breakMinutes,setBreak]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[punchError,setPunchError]=useState(''),[modal,setModal]=useState(null);
 const request=useRef(null),running=useRef(false);const punchState={open:data?.open,loading:loading||!data,busy,error};
 const saved=async()=>{setModal(null);await load();};
 async function punch(kind){if(running.current||!canPunch(kind,punchState))return;running.current=true;setBusy(true);setPunchError('');setMessage('正在取得本次定位…');
  try{const loc=await getPunchLocation();if(loc.error){setMessage('');setPunchError(`${loc.message} 未記錄打卡，填寫備註不能取代定位。`);return;}
   if(!request.current||request.current.kind!==kind)request.current={kind,id:crypto.randomUUID()};
   await rpc('spa_attendance_punch',{p_request:request.current.id,p_kind:kind,p_latitude:loc.latitude,p_longitude:loc.longitude,p_accuracy:loc.accuracy,p_reason:reason,p_location_error:'',p_break_minutes:kind==='out'?Number(breakMinutes):0});
   request.current=null;setReason('');setBreak(0);setMessage(kind==='in'?'已記錄上班。下班時請再次打卡。':'已記錄下班，待店主審核後計入薪資工時。');await load();
  }catch(e){setMessage('');setPunchError(errorText(e));await load();}finally{running.current=false;setBusy(false);}
 }
 return <section className="card attendance-workspace"><div className="os-page-title"><div><p className="eyebrow">ATTENDANCE</p><h2>我的出勤打卡</h2><p className="muted">僅在按下打卡時取得位置；所有時間依台灣時間顯示。工時經店主審核後才納入薪資。</p></div><button disabled={busy||loading} onClick={load}>更新出勤</button></div>
 {error&&<p className="alert" role="alert">{error}</p>}{data&&<><div className="attendance-punch-layout"><div><span role="status" className={`attendance-state ${data.open?'is-working':''}`}><i/>{data.open?'上班中':'未上班／已下班'}</span>{data.open&&<p>上班時間：{dateTime(data.open.clock_in)}</p>}<p>{data.settings.address}<br/><span className="muted">門店半徑 {data.settings.radius_m} 公尺 · 定位誤差上限 {data.settings.max_accuracy_m} 公尺</span></p><div className="attendance-punch-actions"><button className="primary attendance-punch" disabled={!canPunch('in',punchState)} onClick={()=>punch('in')}>上班打卡</button><button className="primary attendance-punch" disabled={!canPunch('out',punchState)} onClick={()=>punch('out')}>下班打卡</button></div><p className="muted">{busy?'正在定位／提交，請稍候…':loading?'更新出勤狀態中…':error?'請先更新出勤狀態再打卡。':data.open?'已上班，只能打下班卡。':'目前未上班，只能打上班卡。'}每次打卡都會重新取得位置。</p></div><div><Field label="異常原因／備註（超出範圍或班表異常時必填）"><textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：室內定位不準、臨時調班"/></Field>{data.open&&<Field label="本次不計薪休息（分鐘）"><input type="number" min="0" step="1" value={breakMinutes} onChange={e=>setBreak(e.target.value)}/></Field>}<p className="muted">必須取得定位才能打卡。範圍外或定位誤差過大時，填寫原因後留下異常紀錄，由店主審核；不會自動計入薪資。</p><button disabled={busy} onClick={()=>setModal({row:null})}>漏打卡／申請補工時</button></div></div>
 {message&&<p role="status">{message}</p>}{punchError&&<p className="alert" role="alert">{punchError}</p>}<div className="attendance-summary"><span>本期核准工時 <strong>{data.rows.filter(r=>r.status==='approved').reduce((sum,r)=>sum+attendanceMinutes(r),0)} 分鐘</strong></span><span>待審核 <strong>{data.rows.filter(r=>r.status==='pending').length} 筆</strong></span></div>
 <h3>本期出勤紀錄</h3>{!data.rows.length&&<Empty>所選期間沒有出勤紀錄。</Empty>}{data.rows.map(row=><AttendanceRow key={row.id} row={row} events={data.events.filter(e=>e.attendance_id===row.id)} action={<div className="actions"><button disabled={busy||data.requests.some(r=>r.attendance_id===row.id&&r.status==='pending')} onClick={()=>setModal({row})}>申請補卡／更正</button></div>}/>)}
 {data.open&&!data.rows.some(r=>r.id===data.open.id)&&<AttendanceRow row={data.open} events={data.events.filter(e=>e.attendance_id===data.open.id)} action={<button onClick={()=>setModal({row:data.open})}>申請補卡／更正</button>}/>}
 <h3>補打卡與更正申請</h3>{!data.requests.length&&<Empty>目前沒有申請。</Empty>}{data.requests.map(r=><div className="attendance-row" key={r.id}><strong>{r.work_date} · {{pending:'待審核',approved:'已核准',rejected:'已退回'}[r.status]}</strong><p>{dateTime(r.proposed_start)} ～ {dateTime(r.proposed_end)} · 休息 {r.break_minutes} 分鐘</p><p>{r.reason}</p>{r.review_note&&<p className="muted">審核：{r.review_note}</p>}</div>)}
 </>}{!data&&!error&&<Empty>載入出勤資料…</Empty>}{modal&&<Modal title="補打卡／工時更正申請" onClose={()=>setModal(null)}><CorrectionForm row={modal.row} saved={saved}/></Modal>}</section>;
}
function CorrectionForm({row,saved}){
 const [date,setDate]=useState(row?.work_date||taipeiDate()),[start,setStart]=useState(taipeiInput(row?.effective_start)),[end,setEnd]=useState(taipeiInput(row?.effective_end)),[rest,setRest]=useState(row?.break_minutes||0),[reason,setReason]=useState('');
 return <MutationForm action={id=>rpc('spa_attendance_request',{p_request:id,p_attendance:row?.id||null,p_date:date,p_start:attendanceStamp(start,row?.effective_start),p_end:attendanceStamp(end,row?.effective_end),p_break_minutes:Number(rest),p_reason:reason})} onSaved={saved} submit="送交店主審核"><p className="muted">填寫實際工時，不會改寫原始打卡。營業日是班表開始的日期；凌晨跨夜班請選前一日。</p><TimeFields date={date} setDate={row?null:setDate} start={start} setStart={setStart} end={end} setEnd={setEnd} rest={rest} setRest={setRest}/><Field label="申請原因"><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field></MutationForm>;
}
function TimeFields({date,setDate,start,setStart,end,setEnd,rest,setRest}){return <div className="form-grid"><Field label="營業日"><input type="date" required max={taipeiDate()} disabled={!setDate} value={date} onChange={e=>setDate?.(e.target.value)}/></Field><Field label="不計薪休息（分鐘）"><input required type="number" min="0" step="1" value={rest} onChange={e=>setRest(e.target.value)}/></Field><Field label="實際開始（台灣時間）"><input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="實際結束（台灣時間）"><input required type="datetime-local" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></Field></div>;}

export function AttendanceManager(){
 const [from,setFrom]=useState(()=>taipeiDate().slice(0,8)+'01'),[to,setTo]=useState(taipeiDate),[filter,setFilter]=useState('attention'),[person,setPerson]=useState('all'),[modal,setModal]=useState(null);
 const {data,error,loading,load}=useAttendance('spa_attendance_admin',from,to);const saved=async()=>{setModal(null);await load();};
 const rows=(data?.rows||[]).filter(r=>(person==='all'||r.staff_id===person)&&(filter==='all'||filter==='attention'&&['open','pending'].includes(r.status)||r.status===filter));
 return <section className="card attendance-workspace"><div className="os-page-title"><div><p className="eyebrow">ATTENDANCE CONTROL</p><h2>出勤與打卡審核</h2><p className="muted">店主專用。核准工時直接進入薪資；加班費仍使用「薪資與提成」的加班核准流程。</p></div><div className="actions"><button disabled={!data} onClick={()=>setModal({kind:'settings'})}>打卡範圍設定</button><button disabled={loading} onClick={load}>更新</button></div></div>
 <div className="toolbar"><Field label="出勤開始日期"><input type="date" required value={from} max={to} onChange={e=>setFrom(e.target.value)}/></Field><Field label="出勤結束日期"><input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="出勤狀態"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="attention">待處理／上班中</option><option value="all">全部出勤</option>{Object.entries(attendanceStatuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="出勤人員"><select value={person} onChange={e=>setPerson(e.target.value)}><option value="all">全部人員</option>{[...new Map((data?.rows||[]).map(r=>[r.staff_id,r])).values()].map(r=><option key={r.staff_id} value={r.staff_id}>{r.employee}</option>)}</select></Field><button disabled={!rows.length} onClick={()=>exportCSV('出勤紀錄.csv',rows.map(r=>({人員:r.employee,營業日:r.work_date,原始上班:r.clock_in?dateTime(r.clock_in):'',原始下班:r.clock_out?dateTime(r.clock_out):'',核算開始:r.effective_start?dateTime(r.effective_start):'',核算結束:r.effective_end?dateTime(r.effective_end):'',休息分鐘:r.break_minutes,淨工時分鐘:attendanceMinutes(r),狀態:attendanceStatuses[r.status],異常:(r.flags||[]).map(f=>attendanceFlags[f]||f).join('、'),審核說明:r.review_note})))}>匯出出勤 CSV</button></div>
 {error&&<p role="alert" className="alert">{error}</p>}{data&&<><p className="muted">{data.settings.address} · 打卡半徑 {data.settings.radius_m} 公尺。未下班的跨期紀錄也會列入待處理。</p><div className="attendance-summary"><span>待審核 <strong>{data.rows.filter(r=>r.status==='pending').length} 筆</strong></span><span>上班中 <strong>{data.rows.filter(r=>r.status==='open').length} 人</strong></span><span>待處理申請 <strong>{data.requests.filter(r=>r.status==='pending').length} 筆</strong></span></div>
 <h3>補打卡與更正申請</h3>{!data.requests.some(r=>r.status==='pending')&&<Empty>沒有待處理申請。</Empty>}{data.requests.filter(r=>r.status==='pending'&&(person==='all'||r.staff_id===person)).map(r=><article className="attendance-row" key={r.id}><strong>{r.employee} · {r.work_date}</strong><p>{dateTime(r.proposed_start)} ～ {dateTime(r.proposed_end)} · 休息 {r.break_minutes} 分鐘</p><p>{r.reason}</p><button onClick={()=>setModal({kind:'request',row:r})}>審核申請</button></article>)}
 <h3>出勤紀錄</h3>{!rows.length&&<Empty>此篩選沒有出勤紀錄。</Empty>}{rows.map(row=><AttendanceRow key={row.id} row={row} events={data.events.filter(e=>e.attendance_id===row.id)} action={<div className="actions"><button onClick={()=>setModal({kind:'review',row})}>{row.status==='approved'?'更正／撤回核准':'審核工時'}</button></div>}/>)}</>}
 {modal&&<Modal title={{settings:'門店打卡範圍',request:'審核補打卡／更正',review:'審核出勤工時'}[modal.kind]} onClose={()=>setModal(null)}>{modal.kind==='settings'?<AttendanceSettings value={data.settings} saved={saved}/>:modal.kind==='request'?<RequestReview row={modal.row} saved={saved}/>:<AttendanceReview row={modal.row} saved={saved}/>}</Modal>}</section>;
}
function AttendanceReview({row,saved}){
 const [start,setStart]=useState(taipeiInput(row.effective_start)),[end,setEnd]=useState(taipeiInput(row.effective_end)),[rest,setRest]=useState(row.break_minutes),[approve,setApprove]=useState(true),[reason,setReason]=useState('');
 return <MutationForm action={()=>rpc('spa_attendance_review',{p_attendance:row.id,p_version:row.version,p_approve:approve,p_start:attendanceStamp(start,row?.effective_start),p_end:attendanceStamp(end,row?.effective_end),p_break_minutes:Number(rest),p_reason:reason})} onSaved={saved} submit={approve?'核准並同步薪資工時':'退回／撤回核准'}><p>{row.employee} · {row.work_date}</p><Field label="審核結果"><select value={String(approve)} onChange={e=>setApprove(e.target.value==='true')}><option value="true">核准工時</option><option value="false">退回／撤回核准</option></select></Field>{approve&&<TimeFields date={row.work_date} start={start} setStart={setStart} end={end} setEnd={setEnd} rest={rest} setRest={setRest}/>}<Field label="審核原因（必填）"><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="muted">核准後自動連動薪資工時。修改保留原始紀錄；已結算期間須先在薪資系統重新開啟，重複工時會被阻止。</p></MutationForm>;
}
function RequestReview({row,saved}){const [approve,setApprove]=useState(true),[reason,setReason]=useState('');return <MutationForm action={()=>rpc('spa_attendance_request_review',{p_request:row.id,p_approve:approve,p_reason:reason})} onSaved={saved} submit="確認審核"><p>{row.employee} · {row.work_date}</p><p>{dateTime(row.proposed_start)} ～ {dateTime(row.proposed_end)} · 休息 {row.break_minutes} 分鐘</p><p>員工原因：{row.reason}</p><Field label="審核結果"><select value={String(approve)} onChange={e=>setApprove(e.target.value==='true')}><option value="true">核准並同步薪資工時</option><option value="false">退回</option></select></Field><Field label="審核原因"><textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field></MutationForm>;}
export function AttendanceSettings({value,saved}){
 const [f,setF]=useState(value);const set=(key,v)=>setF(s=>({...s,[key]:v}));
 return <MutationForm action={()=>rpc('spa_attendance_setting_save',{p_latitude:Number(f.latitude),p_longitude:Number(f.longitude),p_radius:Number(f.radius_m),p_accuracy:Number(f.max_accuracy_m),p_grace:Number(f.grace_minutes),p_max_shift:Number(f.max_shift_minutes),p_address:f.address})} onSaved={saved} submit="儲存打卡範圍"><p className="muted">預設沿用官網地址的地圖標記。修改只影響新的打卡；舊紀錄保留當時的範圍設定。</p><div className="form-grid"><Field wide label="門店定位地址"><input required maxLength={200} value={f.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="門店緯度"><input required type="number" step="any" min="-90" max="90" value={f.latitude} onChange={e=>set('latitude',e.target.value)}/></Field><Field label="門店經度"><input required type="number" step="any" min="-180" max="180" value={f.longitude} onChange={e=>set('longitude',e.target.value)}/></Field>{[['radius_m','打卡半徑（公尺）',20,2000],['max_accuracy_m','定位誤差上限（公尺）',5,500],['grace_minutes','遲到／早退寬限（分鐘）',0,60],['max_shift_minutes','未下班異常門檻（分鐘）',60,2880]].map(([key,label,min,max])=><Field label={label} key={key}><input required type="number" step="1" min={min} max={max} value={f[key]} onChange={e=>set(key,e.target.value)}/></Field>)}</div><p><a href={`https://www.google.com/maps?q=${f.latitude},${f.longitude}`} target="_blank" rel="noreferrer">核對門店地圖標記</a></p><p className="muted">瀏覽器定位可能被偽造，位置紀錄供店主審核參考。未取得定位不能打卡，請改送補打卡申請。</p></MutationForm>;
}
