import { useEffect, useState } from 'react';
import { supabase, rpc, errorText, money, dateTime, statusNames } from './lib/spa.js';
import { useSession, Login, Empty, PrivateLink } from './OperationsShared.jsx';
export default function Member(){
 const session=useSession(),[detail,setDetail]=useState(null),[error,setError]=useState(''),[linked,setLinked]=useState(undefined);
 useEffect(()=>{setDetail(null);setLinked(undefined);setError('');if(!session)return;let live=true;rpc('spa_session').then(async access=>{if(!live)return;setLinked(!!access.customer_id);if(access.customer_id){const d=await rpc('spa_customer_detail',{p_customer:access.customer_id});if(live)setDetail(d);}}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[session?.user?.id]);
 if(session===undefined)return <div className="ops"><Empty>載入中…</Empty></div>;
 if(!session)return <Login title="會員中心"/>;
 return <div className="ops"><main><header><div><h1>會員中心</h1><p>{session.user.email}</p></div><div className="row"><a href="#">返回首頁</a><button onClick={()=>supabase.auth.signOut()}>登出</button></div></header>{error&&<p role="alert" className="alert">{error}</p>}{linked===false&&<div className="card"><p>請聯絡門店，將登入帳號綁定到您的會員資料。</p><p>綁定完成後即可查看餘額與療程歷史。</p></div>}{detail?<><div className="grid"><div className="card"><h3>可用儲值 credits</h3><div className="metric">{money(detail.wallet.reduce((n,w)=>n+Number(w.amount_cents),0))}</div></div></div><h2>我的療程套票</h2><div className="grid">{detail.packages.map(p=><div className="card" key={p.id}><h3>{p.name}</h3><p>{p.service_name}</p><div className="metric">{p.remaining} / {p.sessions} 次</div><p className="muted">{new Date(p.expires_at)<new Date()?'已到期':'有效至'} {dateTime(p.expires_at)}</p></div>)}</div>{!detail.packages.length&&<Empty/>}<h2>預約與評價</h2>{detail.appointments.map(a=><div className="card" style={{marginTop:14}} key={a.id}><h3>{a.service_name} · {statusNames[a.status]}</h3><p>{dateTime(a.starts_at)} · {a.reference}</p><PrivateLink path={`manage/${a.manage_token}`} label="管理預約"/>{a.review_token&&<PrivateLink path={`review/${a.review_token}`} label="填寫療程評價"/>}</div>)}<h2 style={{marginTop:28}}>我的儲值流水</h2><div className="table-wrap"><table><thead><tr><th>時間</th><th>金額</th><th>項目</th></tr></thead><tbody>{detail.wallet.map(w=><tr key={w.id}><td>{dateTime(w.created_at)}</td><td>{money(w.amount_cents)}</td><td>{w.note}</td></tr>)}</tbody></table></div></>:linked!==false&&!error?<Empty>正在載入會員資料…</Empty>:null}</main></div>;
}
