import { useState } from 'react';
import { rpc, errorText, money, dateTime, statusNames } from './lib/spa.js';
import { statusNamesEn, therapistLabel } from './lib/public-copy.js';
import './booking-lookup.css';

export default function Member({lang='zh'}){
 const [name,setName]=useState(''),[phone,setPhone]=useState(''),[access,setAccess]=useState(null),[detail,setDetail]=useState(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reviewing,setReviewing]=useState(null);
 const en=lang==='en',t=(zh,english)=>en?english:zh;
 async function login(event){event.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const result=await rpc('spa_member_login',{p_phone:phone.trim(),p_name:name.trim()});if(!result?.member){setDetail(null);setAccess(null);setError(t('找不到相符的會員資料，請確認姓名與手機和預約時完全一致。','No matching member profile. Use the exact name and phone number from your booking.'));return;}setAccess(result.access_token);setDetail(result.member);}catch(e){setError(errorText(e,lang));}finally{setBusy(false);}}
 async function refresh(token=access){if(!token)return;const next=await rpc('spa_member_detail',{p_access:token});setDetail(next);return next;}
 function logout(){setAccess(null);setDetail(null);setReviewing(null);setNotice('');setError('');}
 const coupons=detail?.coupons||[],usable=coupons.filter(item=>item.status==='active'),appointments=detail?.appointments||[],orders=detail?.orders||[],packages=detail?.packages||[];
 return <main className="lookup-page member-page"><div className="booking-lookup member-shell">
  <header className="lookup-header"><div><p className="lookup-eyebrow">ROU SPA · MEMBER</p><h1>{t('會員中心','Member centre')}</h1></div><div className="member-header-actions"><a href="#">{t('返回首頁','Home')}</a>{detail&&<button onClick={logout}>{t('登出','Sign out')}</button>}</div></header>
  {!detail?<form className="lookup-form member-login" onSubmit={login}><h2>{t('姓名＋手機登入','Sign in with name and phone')}</h2><p className="lookup-intro">{t('第一次完成預約時，系統已自動建立會員資料；不需要註冊、Email 或密碼。','Your member profile is created automatically with your first booking. No email, registration or password is needed.')}</p><div className="lookup-fields"><label>{t('預約姓名','Booking name')}<input required autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder={t('請輸入完整姓名','Full name')}/></label><label>{t('手機號碼','Phone number')}<input required type="tel" inputMode="tel" autoComplete="tel" maxLength={25} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09xxxxxxxx"/></label></div><button className="lookup-primary" disabled={busy}>{busy?t('登入中…','Signing in…'):t('進入會員中心','Open member centre')}</button><p className="lookup-help">{t('姓名與手機必須和預約資料完全一致。登入只保留在目前頁面，兩小時後自動失效。','Both details must exactly match your booking. Access stays in this page and expires after two hours.')}</p></form>:
  <><section className="member-welcome"><div><p className="lookup-eyebrow">WELCOME BACK</p><h2>{detail.profile?.name}</h2><p>{detail.profile?.tier} · {detail.profile?.phone}</p></div><span>{t('會員資料已驗證','Member verified')}</span></section>
   <div className="member-metrics"><article><span>{t('儲值餘額','Wallet balance')}</span><strong>{money(detail.wallet_balance_cents)}</strong></article><article><span>{t('可用優惠券','Available coupons')}</span><strong>{usable.length}</strong><small>{t(`共 ${money(usable.reduce((sum,item)=>sum+Number(item.amount_cents),0))}`,`${money(usable.reduce((sum,item)=>sum+Number(item.amount_cents),0))} total`)}</small></article><article><span>{t('已完成療程','Completed visits')}</span><strong>{appointments.filter(item=>item.status==='completed').length}</strong></article><article><span>{t('療程套票','Packages')}</span><strong>{packages.filter(item=>Number(item.remaining)>0&&new Date(item.expires_at)>new Date()).length}</strong></article></div>
   {notice&&<p className="lookup-success" role="status">{notice}</p>}
   <MemberSection title={t('優惠券','Coupons')} subtitle={t('完成療程並留下評價，可獲得 NT$50 優惠券；每筆預約限領一次。','Review a completed visit to receive one NT$50 coupon per booking.')} empty={t('目前沒有優惠券。完成療程後留下評價，即可獲得第一張。','No coupons yet. Review a completed treatment to receive your first one.')} rows={coupons} render={coupon=><article className={`member-coupon ${coupon.status!=='active'?'used':''}`} key={coupon.id}><div><p className="lookup-eyebrow">{coupon.status==='active'?t('可使用','AVAILABLE'):coupon.status==='redeemed'?t('已使用','REDEEMED'):coupon.status==='expired'?t('已到期','EXPIRED'):t('已作廢','VOID')}</p><h3>{coupon.title}</h3><p>{coupon.code}</p><small>{t('有效至','Valid until')} {dateTime(coupon.expires_at,lang)}</small></div><strong>{money(coupon.amount_cents)}</strong></article>}/>
   <MemberSection title={t('預約與療程記錄','Bookings and visits')} subtitle={t('門店確認療程完成後，評價會歸到實際服務技師，並自動發券。','Once the store confirms completion, your review goes to the actual therapist and the coupon is issued automatically.')} empty={t('目前沒有預約記錄。','No bookings yet.')} rows={appointments} render={row=><article className="lookup-card member-visit" key={row.id}><div className="lookup-card-heading"><h3>{row.service_name}</h3><span className="lookup-status">{(en?statusNamesEn:statusNames)[row.status]}</span></div><p className="lookup-reference">{row.reference}</p><p>{dateTime(row.starts_at,lang)} · {t('服務技師','Therapist')}：{therapistLabel(row,lang)}</p><p>{money(row.price_cents)}</p>{row.review_submitted&&<p className="lookup-success">{t('已完成評價；回饋券可在上方查看。','Review submitted. Your reward coupon appears above.')}</p>}{row.can_review&&!row.review_submitted&&<><button className="lookup-primary member-review-button" onClick={()=>setReviewing(reviewing===row.id?null:row.id)}>{t('評價技師 · 領 NT$50 優惠券','Review therapist · Get NT$50')}</button>{reviewing===row.id&&<MemberReview access={access} row={row} lang={lang} close={()=>setReviewing(null)} saved={async()=>{await refresh();setReviewing(null);setNotice(t('謝謝您的評價，NT$50 優惠券已發放到會員中心。','Thank you. Your NT$50 coupon is now in your member centre.'));}}/>}</>}</article>}/>
   <MemberSection title={t('門店訂單','Store orders')} subtitle={t('顯示有綁定會員的 POS 商品與服務訂單。','POS product and service orders linked to your member profile.')} empty={t('目前沒有門店訂單。','No store orders yet.')} rows={orders} render={order=><article className="member-order" key={order.id}><div className="lookup-card-heading"><h3>{order.reference}</h3><span className="lookup-status">{{paid:t('已付款','Paid'),draft:t('草稿','Draft'),void:t('已作廢','Void'),refunded:t('已退款','Refunded')}[order.status]||order.status}</span></div><p>{dateTime(order.paid_at||order.created_at,lang)} · {money(order.total_cents)}</p><ul>{order.items.map(item=><li key={item.id}><span>{item.name} × {item.quantity}</span><strong>{money(item.line_total_cents)}</strong></li>)}</ul></article>}/>
   <MemberSection title={t('我的療程套票','Treatment packages')} empty={t('目前沒有療程套票。','No treatment packages.')} rows={packages} render={item=><article className="member-package" key={item.id}><div><h3>{item.name}</h3><p>{item.service_name}</p><small>{t('有效至','Valid until')} {dateTime(item.expires_at,lang)}</small></div><strong>{item.remaining} / {item.sessions} {t('次','visits')}</strong></article>}/>
  </>}
  {error&&<p role="alert" className="lookup-alert">{error}</p>}
 </div></main>;
}

function MemberSection({title,subtitle,empty,rows,render}){return <section className="member-section"><div className="member-section-heading"><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{rows.length?<div className="member-list">{rows.map(render)}</div>:<p className="lookup-empty">{empty}</p>}</section>;}

function MemberReview({access,row,lang,close,saved}){
 const [rating,setRating]=useState('5'),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const t=(zh,en)=>lang==='en'?en:zh;
 async function submit(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await rpc('spa_customer_review',{p_access:access,p_appointment:row.id,p_rating:Number(rating),p_comment:comment});await saved();}catch(e){setError(errorText(e,lang));}finally{setBusy(false);}}
 return <form className="lookup-change" onSubmit={submit}><h4>{t('評價實際服務技師','Review your actual therapist')} · {therapistLabel(row,lang)}</h4><label>{t('服務評分','Rating')}<select value={rating} onChange={e=>setRating(e.target.value)}>{[5,4,3,2,1].map(value=><option value={value} key={value}>{'★'.repeat(value)} {value} / 5</option>)}</select></label><label>{t('您的體驗（最多 1000 字）','Your experience (up to 1,000 characters)')}<textarea rows={3} maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label><p className="lookup-help">{t('提交成功後會立即發放 NT$50 優惠券。每次療程限評價和領取一次。','An NT$50 coupon is issued immediately after submission. One review and reward per treatment.')}</p>{error&&<p className="lookup-alert">{error}</p>}<div className="lookup-actions"><button type="button" disabled={busy} onClick={close}>{t('返回','Back')}</button><button className="lookup-primary" disabled={busy}>{busy?t('提交中…','Submitting…'):t('提交評價並領券','Submit and get coupon')}</button></div></form>;
}
