import { useEffect, useMemo, useRef, useState } from 'react';
import { errorText, money, publicRpc, taipeiDate } from './lib/spa.js';
import { publicName, publicTitle, therapistLabel, slotLabel } from './lib/public-copy.js';
import { useBookingClock } from './lib/useBookingClock.js';

const copy={zh:{steps:['選擇服務','預約方式','日期時段','確認預約'],service:'請選擇服務項目',method:'您想怎麼找時間？',staff:'指定技師',staffSub:'先選技師，再看她本月與下月的班表。',time:'挑時間',timeSub:'先挑日期與時間，再看當時有空的技師。',any:'不指定技師，由店家安排',anySub:'系統會在有空的合格技師中，優先安排當天服務分鐘較少的人。',next:'下一步',back:'上一步',chooseStaff:'選擇指定技師',chooseDate:'只開放本月與下個月',chooseSlot:'選擇可預約時段',chooseAfter:'這個時間可選的技師',noPreference:'不指定，由店家安排',open:'可約',full:'已滿',off:'休',people:'位可約',loading:'正在計算正式班表與空檔…',summary:'預約摘要',name:'您的姓名',phone:'您的手機號碼',note:'備註（選填）',confirm:'確認預約',submitting:'預約中…',success:'預約已送出',again:'重新預約',manage:'查看、取消或改期（請保存此私人連結）',member:'首次預約會以姓名與手機號碼自動建立會員資料，無需 Email 或另外註冊。',assigned:'實際安排技師',designated:'指定技師',automatic:'店家自動安排'},en:{steps:['Service','Booking method','Date & time','Confirm'],service:'Choose a service',method:'How would you like to book?',staff:'Choose a therapist',staffSub:'Select a therapist, then view their roster for this and next month.',time:'Choose a time',timeSub:'Select a date and time, then choose from available therapists.',any:'No preference',anySub:'We assign an available qualified therapist with the lightest workload that day.',next:'Next',back:'Back',chooseStaff:'Select your therapist',chooseDate:'Available for this and next month',chooseSlot:'Choose an available time',chooseAfter:'Therapists available at this time',noPreference:'No preference — let the store assign',open:'Open',full:'Full',off:'Off',people:'available',loading:'Checking the live roster and availability…',summary:'Booking summary',name:'Full name',phone:'Phone number',note:'Notes (optional)',confirm:'Confirm booking',submitting:'Submitting…',success:'Booking received',again:'Book again',manage:'Manage booking — save this private link',member:'Your first booking creates a member profile with your name and phone. No email or separate registration is needed.',assigned:'Assigned therapist',designated:'Requested therapist',automatic:'Assigned by store'}};

function monthKey(value,step=0){const [y,m]=value.slice(0,7).split('-').map(Number),d=new Date(Date.UTC(y,m-1+step,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function monthCells(month){const [y,m]=month.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)),pad=(first.getUTCDay()+6)%7,last=new Date(Date.UTC(y,m,0)).getUTCDate(),cells=Array(pad).fill(null);for(let d=1;d<=last;d++)cells.push(`${month}-${String(d).padStart(2,'0')}`);while(cells.length%7)cells.push(null);return cells;}
function monthLabel(month,lang){const [year,value]=month.split('-');return lang==='zh'?`${year} 年 ${Number(value)} 月`:new Intl.DateTimeFormat('en',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${month}-01T00:00:00Z`));}
function periodOf(label){const clean=label.replace('翌日 ','');const hour=Number(clean.slice(0,2));return label.startsWith('翌日')||hour>=17?'evening':hour<12?'morning':'afternoon';}
const periodNames={zh:{morning:'上午',afternoon:'下午',evening:'晚間'},en:{morning:'Morning',afternoon:'Afternoon',evening:'Evening'}};

export default function PublicBookingExperience({catalog,catalogError,lang='zh'}){
 const c=copy[lang],services=catalog?.services||[],[step,setStep]=useState(0),[serviceId,setServiceId]=useState(''),[method,setMethod]=useState(''),[staffId,setStaffId]=useState(''),[calendars,setCalendars]=useState([]),[calendarBusy,setCalendarBusy]=useState(false),[date,setDate]=useState(''),[slots,setSlots]=useState([]),[slotBusy,setSlotBusy]=useState(false),[start,setStart]=useState(''),[availableStaff,setAvailableStaff]=useState([]),[staffBusy,setStaffBusy]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),[receipt,setReceipt]=useState(null);
 const now=useBookingClock(),request=useRef(null),today=taipeiDate(new Date(now)),currentMonth=monthKey(today),months=[currentMonth,monthKey(today,1)],availabilityStaff=method==='staff'?staffId:null,service=services.find(row=>row.id===serviceId),qualified=(catalog?.staff||[]).filter(st=>(catalog?.skills||[]).some(sk=>sk.staff_id===st.id&&sk.service_id===serviceId&&sk.enabled!==false));
 const chosenStaff=(catalog?.staff||[]).find(row=>row.id===staffId);
 // Only a change to the searched service/method/designated therapist resets the
 // draft. Picking a therapist after a time, or moving to confirmation, keeps it.
 useEffect(()=>{setCalendars([]);setDate('');setStart('');setSlots([]);setAvailableStaff([]);},[serviceId,method,availabilityStaff,currentMonth]);
 useEffect(()=>{if(step!==2||!serviceId||!method||(method==='staff'&&!availabilityStaff))return;let live=true;setCalendarBusy(true);setError('');Promise.all(months.map(month=>publicRpc('spa_booking_calendar',{p_service:serviceId,p_month:`${month}-01`,p_staff:availabilityStaff}))).then(rows=>{if(live){setCalendars(rows);setDate(selected=>!selected||rows.some(calendar=>calendar.days.some(day=>day.date===selected&&day.status==='open'))?selected:'');}}).catch(e=>{if(live)setError(errorText(e,lang));}).finally(()=>{if(live)setCalendarBusy(false);});return()=>{live=false;};},[step,serviceId,method,availabilityStaff,currentMonth]);
 useEffect(()=>{if(step!==2||!date||!serviceId)return;let live=true;setSlotBusy(true);setError('');publicRpc('spa_public_slots',{p_service:serviceId,p_date:date,p_staff:availabilityStaff}).then(rows=>{if(live){setSlots(rows);setStart(selected=>rows.some(row=>row.starts_at===selected&&row.available)?selected:'');}}).catch(e=>{if(live){setSlots([]);setStart('');setError(errorText(e,lang));}}).finally(()=>{if(live)setSlotBusy(false);});return()=>{live=false;};},[step,date,serviceId,method,availabilityStaff]);
 useEffect(()=>{if(method!=='time'||!start){setAvailableStaff([]);return;}let live=true;setStaffBusy(true);publicRpc('spa_public_available_staff',{p_service:serviceId,p_date:date,p_start:start}).then(rows=>{if(live){setAvailableStaff(rows);setStaffId(selected=>selected==='any'&&rows.length||rows.some(row=>row.id===selected)?selected:'');}}).catch(e=>{if(live){setAvailableStaff([]);setStaffId('');setError(errorText(e,lang));}}).finally(()=>{if(live)setStaffBusy(false);});return()=>{live=false;};},[method,start,date,serviceId]);
 const grouped=useMemo(()=>Object.fromEntries(['morning','afternoon','evening'].map(period=>[period,slots.filter(row=>row.available&&periodOf(row.time_label)===period)])),[slots]);
 const canLeaveMethod=method&&!(method==='staff'&&!staffId),canLeaveTime=!calendarBusy&&!slotBusy&&date&&start&&slots.some(row=>row.starts_at===start&&row.available)&&(method!=='time'||(!staffBusy&&availableStaff.length>0&&(staffId==='any'||availableStaff.some(row=>row.id===staffId))));
 function reset(){setStep(0);setServiceId('');setMethod('');setStaffId('');setCalendars([]);setDate('');setSlots([]);setStart('');setAvailableStaff([]);setName('');setPhone('');setNote('');setError('');setReceipt(null);request.current=null;}
 async function submit(){if(submitting)return;setSubmitting(true);setError('');const assigned=method==='any'||staffId==='any'?null:staffId,payload={p_service:serviceId,p_date:date,p_start:start,p_staff:assigned,p_name:name.trim(),p_phone:phone.trim(),p_tea:0,p_note:note},fingerprint=JSON.stringify(payload);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};try{setReceipt(await publicRpc('spa_create_booking',{p_request:request.current.id,...payload}));}catch(e){setError(errorText(e,lang));if(e.message?.includes('SLOT_TAKEN')){setStep(2);setStart('');}}finally{setSubmitting(false);}}
 if(receipt)return <div className="booking-experience booking-success"><div className="booking-check">✓</div><h3>{c.success}</h3><p><strong>{receipt.reference}</strong></p><div className="booking-receipt"><span>{c.assigned}</span><strong>{receipt.staff_name}</strong><small>{receipt.booking_preference==='designated'?c.designated:c.automatic}</small></div><a href={`#manage/${receipt.manage_token}`}>{c.manage}</a><button className="outline-btn" onClick={reset}>{c.again}</button></div>;
 return <div className="booking-experience">
  {(catalogError||error)&&<p className="booking-error" role="alert">{catalogError||error}</p>}
  <ol className="booking-flow-progress">{c.steps.map((label,i)=><li className={i===step?'active':i<step?'done':''} key={label}><i>{i<step?'✓':i+1}</i><span>{label}</span></li>)}</ol>
  {step===0&&<section><h3>{c.service}</h3><div className="booking-service-grid">{services.map(row=><button key={row.id} className={serviceId===row.id?'selected':''} onClick={()=>setServiceId(row.id)}><strong>{publicName(row,lang)}</strong><span>{row.duration_minutes} min · {money(row.price_cents)}</span></button>)}</div><div className="booking-actions"><button className="gold-btn" disabled={!serviceId} onClick={()=>setStep(1)}>{c.next}</button></div></section>}
  {step===1&&<section><h3>{c.method}</h3><div className="booking-method-grid"><button className={method==='staff'?'selected':''} onClick={()=>{setMethod('staff');setStaffId('');}}><b>◎</b><strong>{c.staff}</strong><span>{c.staffSub}</span></button><button className={method==='time'?'selected':''} onClick={()=>{setMethod('time');setStaffId('');}}><b>◷</b><strong>{c.time}</strong><span>{c.timeSub}</span></button></div><button className={`booking-any-method ${method==='any'?'selected':''}`} onClick={()=>{setMethod('any');setStaffId('any');}}><span><strong>{c.any}</strong><small>{c.anySub}</small></span><b>›</b></button>{method==='staff'&&<><h4>{c.chooseStaff}</h4><div className="booking-staff-grid">{qualified.map(row=><button key={row.id} className={staffId===row.id?'selected':''} onClick={()=>setStaffId(row.id)}><i>{row.name.slice(0,1)}</i><span><strong>{publicName(row,lang)}</strong><small>{publicTitle(row,lang)}</small></span></button>)}</div></>}<div className="booking-actions"><button className="outline-btn" onClick={()=>setStep(0)}>{c.back}</button><button className="gold-btn" disabled={!canLeaveMethod} onClick={()=>setStep(2)}>{c.next}</button></div></section>}
  {step===2&&<section><h3>{c.chooseDate}</h3>{calendarBusy?<p className="booking-loading">{c.loading}</p>:<div className="booking-two-months">{calendars.map(calendar=><article key={calendar.month}><h4>{monthLabel(calendar.month,lang)}</h4><div className="booking-calendar-week">{(lang==='zh'?['一','二','三','四','五','六','日']:['M','T','W','T','F','S','S']).map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div><div className="booking-calendar-grid">{monthCells(calendar.month).map((day,i)=>{if(!day)return <span className="blank" key={`blank-${i}`}/>;const row=calendar.days.find(item=>item.date===day),enabled=row?.status==='open';return <button key={day} disabled={!enabled} className={`${row?.status||'off'} ${date===day?'selected':''}`} onClick={()=>setDate(day)}><strong>{Number(day.slice(-2))}</strong><small>{row?.status==='open'?(method==='staff'?`${String(Math.floor(row.start_minute/60)%24).padStart(2,'0')}:${String(row.start_minute%60).padStart(2,'0')}–${String(Math.floor(row.end_minute/60)%24).padStart(2,'0')}:${String(row.end_minute%60).padStart(2,'0')}`:`${row.available_staff} ${c.people}`):row?.status==='full'?c.full:row?.status==='past'?'':c.off}</small></button>;})}</div></article>)}</div>}
  {date&&<><h4>{c.chooseSlot} · {date}</h4>{slotBusy?<p className="booking-loading">{c.loading}</p>:<div className="booking-slot-groups">{Object.entries(grouped).map(([period,rows])=>rows.length?<div key={period}><h5>{periodNames[lang][period]}</h5><div>{rows.map(row=><button key={row.starts_at} className={start===row.starts_at?'selected':''} onClick={()=>{setStart(row.starts_at);if(method==='time')setStaffId('');}}><strong>{slotLabel(row.time_label,lang)}</strong>{method!=='staff'&&<small>{row.available_staff_count} {c.people}</small>}</button>)}</div></div>:null)}</div>}</>}
  {method==='time'&&start&&<><h4>{c.chooseAfter}</h4><div className="booking-staff-grid after-time"><button className={staffId==='any'?'selected':''} onClick={()=>setStaffId('any')}><i>✦</i><span><strong>{c.noPreference}</strong><small>{c.automatic}</small></span></button>{availableStaff.map(row=><button key={row.id} className={staffId===row.id?'selected':''} onClick={()=>setStaffId(row.id)}><i>{row.name.slice(0,1)}</i><span><strong>{publicName(row,lang)}</strong><small>{publicTitle(row,lang)}</small></span></button>)}</div></>}
  <div className="booking-actions"><button className="outline-btn" onClick={()=>setStep(1)}>{c.back}</button><button className="gold-btn" disabled={!canLeaveTime} onClick={()=>setStep(3)}>{c.next}</button></div></section>}
  {step===3&&<section><h3>{c.summary}</h3><dl className="booking-summary"><dt>{lang==='zh'?'服務':'Service'}</dt><dd>{publicName(service,lang)}</dd><dt>{lang==='zh'?'預約方式':'Method'}</dt><dd>{method==='staff'?therapistLabel(chosenStaff,lang):method==='time'&&staffId!=='any'?therapistLabel(chosenStaff,lang):c.any}</dd><dt>{lang==='zh'?'日期／時間':'Date / time'}</dt><dd>{date} · {slotLabel(slots.find(row=>row.starts_at===start)?.time_label,lang)}</dd><dt>{lang==='zh'?'費用':'Price'}</dt><dd>{money(service?.price_cents)}</dd></dl><div className="booking-contact-form"><input autoComplete="name" maxLength="80" value={name} onChange={e=>setName(e.target.value)} placeholder={c.name}/><input autoComplete="tel" type="tel" maxLength="25" value={phone} onChange={e=>setPhone(e.target.value)} placeholder={c.phone}/><p>{c.member}</p><textarea maxLength="1000" rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder={c.note}/></div><div className="booking-actions"><button className="outline-btn" onClick={()=>setStep(2)}>{c.back}</button><button className="gold-btn" disabled={!name.trim()||!phone.trim()||submitting} onClick={submit}>{submitting?c.submitting:c.confirm}</button></div></section>}
 </div>;
}
